### PR TITLE
wait indefinitely until all subscriptions acknowledge the messages.

### LINKED ISSUE #822: minimal_publisher_with_wait_for_all_acked: Not all subscribers acknowledge
### Operating System:

ghcr.io/sloretz/ros-testing:kilted-desktop

### ROS version or commit hash:

kilted

### RMW implementation (if applicable):

rmw_fastrtps

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

https://docs.ros.org/en/kilted/Tutorials/Demos/Wait-for-Acknowledgment.html

### Expected behavior

All messages ack

### Actual behavior

Not all messages ack

### Additional information

Not all subscribers acknowledge messags when running `minimal_publisher_with_wait_for_all_acked`: 

https://github.com/ros2/kilted_tutorial_party/issues/542#issuecomment-2845988577

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rmw_fastrtps/issues/822

### CODE REVIEW

File: rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp [hunk 1]
```diff
@@ -30,7 +30,7 @@ class MinimalPublisher : public rclcpp::Node
   MinimalPublisher()
   : Node("minimal_publisher_with_wait_for_all_acked"),
     count_(0),
-    wait_timeout_(300)
+    wait_timeout_(-1)
```
Comment (fujitatomoya) [inline rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp]: see my comment https://github.com/ros2/rmw_fastrtps/issues/822#issuecomment-2867977437

@Barry-Xu-2018 @MiguelCompany do you think any downside of this?

Comment (Barry-Xu-2018) [reply rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp]: @fujitatomoya 

Maybe we can set a longer wait time. Otherwise, the code from line 61-66 needs to be removed because when the timeout is -1, the else part of the code will never be executed.

Comment (fujitatomoya) [reply rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp]: yeah i though that too. longer timeout could be safer than infinite timeout? if you prefer that, how about 5 seconds? i am almost sure, with 5 seconds this problem should never happen unless something else goes wrong.

Comment (Barry-Xu-2018) [reply rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp]: I think it is okay.

Comment (MiguelCompany) [reply rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp]: I agree. Five seconds should be more than enough.

Comment (fujitatomoya) [reply rclcpp/topics/minimal_publisher/member_function_with_wait_for_all_acked.cpp]: okay, let's do that instead! thanks for the comment.

**Comment by fujitatomoya** [comment]
Pulls: ros2/examples#414
Gist: https://gist.githubusercontent.com/fujitatomoya/158f6b105354c01a9a8465d7e5b54c6b/raw/223f3eb03c0c916c65e9701c2e3071c5ce957f0f/ros2.repos
BUILD args:  --packages-above-and-dependencies examples_rclcpp_minimal_publisher
TEST args:  --packages-above examples_rclcpp_minimal_publisher
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15967
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23595/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17711/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3055/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24328/)

**Review by Barry-Xu-2018 — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@Mergifyio backport kilted jazzy humble
